<a href="https://colab.research.google.com/github/atta-hilali/Machine_Learning/blob/main/Titanic_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [88]:
df=pd.read_csv("train.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [89]:
from sklearn.impute import SimpleImputer

imputer=SimpleImputer(missing_values=np.nan,strategy="most_frequent")
df=pd.DataFrame(imputer.fit_transform(df))
df

0  1  2                                                  3       4   \
0      1  0  3                            Braund, Mr. Owen Harris    male   
1      2  1  1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2      3  1  3                             Heikkinen, Miss. Laina  female   
3      4  1  1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4      5  0  3                           Allen, Mr. William Henry    male   
..   ... .. ..                                                ...     ...   
886  887  0  2                              Montvila, Rev. Juozas    male   
887  888  1  1                       Graham, Miss. Margaret Edith  female   
888  889  0  3           Johnston, Miss. Catherine Helen "Carrie"  female   
889  890  1  1                              Behr, Mr. Karl Howell    male   
890  891  0  3                                Dooley, Mr. Patrick    male   

       5  6  7                 8        9        10 11  
0    22.0  1  0         A/5 21171     7.25  B96 B98  S  
1    38.0  1  0          PC 17599  71.2833      C85  C  
2    26.0  0  0  STON/O2. 3101282    7.925  B96 B98  S  
3    35.0  1  0            113803     53.1     C123  S  
4    35.0  0  0            373450     8.05  B96 B98  S  
..    ... .. ..               ...      ...      ... ..  
886  27.0  0  0            211536     13.0  B96 B98  S  
887  19.0  0  0            112053     30.0      B42  S  
888  24.0  1  2        W./C. 6607    23.45  B96 B98  S  
889  26.0  0  0            111369     30.0     C148  C  
890  32.0  0  0            370376     7.75  B96 B98  Q  

[891 rows x 12 columns]

In [90]:
x=df.iloc[:,4:-1].values
y=df.iloc[:,1].values
x=pd.DataFrame(x)



In [91]:
x

0     1  2  3                 4        5        6
0      male  22.0  1  0         A/5 21171     7.25  B96 B98
1    female  38.0  1  0          PC 17599  71.2833      C85
2    female  26.0  0  0  STON/O2. 3101282    7.925  B96 B98
3    female  35.0  1  0            113803     53.1     C123
4      male  35.0  0  0            373450     8.05  B96 B98
..      ...   ... .. ..               ...      ...      ...
886    male  27.0  0  0            211536     13.0  B96 B98
887  female  19.0  0  0            112053     30.0      B42
888  female  24.0  1  2        W./C. 6607    23.45  B96 B98
889    male  26.0  0  0            111369     30.0     C148
890    male  32.0  0  0            370376     7.75  B96 B98

[891 rows x 7 columns]

In [92]:
df[0]=pd.to_numeric(df[0],errors="coerce")
df[2]=pd.to_numeric(df[2],errors="coerce")
df[6]=pd.to_numeric(df[6],errors="coerce")


In [93]:
ct=[0,2,6]
nt=[1,3,5]
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
co=ColumnTransformer(transformers=(["categorie",OneHotEncoder(sparse_output=False),ct],["numerique",StandardScaler(),nt]),remainder="drop")
x_trans=(co.fit_transform(x))
x_trans

array([[ 0.        ,  1.        ,  0.        , ..., -0.49779327,
        -0.47367361, -0.50244517],
       [ 1.        ,  0.        ,  0.        , ...,  0.71504807,
        -0.47367361,  0.78684529],
       [ 1.        ,  0.        ,  1.        , ..., -0.19458293,
        -0.47367361, -0.48885426],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.3461881 ,
         2.00893337, -0.17626324],
       [ 0.        ,  1.        ,  1.        , ..., -0.19458293,
        -0.47367361, -0.04438104],
       [ 0.        ,  1.        ,  1.        , ...,  0.26023257,
        -0.47367361, -0.49237783]])

In [94]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [102]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_trans,y,test_size=0.2,random_state=0)
y_train




array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,

In [100]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
# Convert y_train to a suitable data type for classification
y_train = y_train.astype(int)  # Assuming y_train contains numerical values that can be cast to integers
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [106]:
from sklearn.naive_bayes import GaussianNB
classifier1 = GaussianNB()
y_train = y_train.astype(int)
classifier1.fit(x_train, y_train)

GaussianNB()

In [112]:
from sklearn.neighbors import KNeighborsClassifier
classifier2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier2.fit(x_train, y_train)

KNeighborsClassifier()

In [113]:
y_pred1=classifier1.predict(x_test)
y_pred2=classifier1.predict(x_test)

In [110]:
# Convert y_test to numeric type, ensuring consistency with y_pred.
y_test = pd.to_numeric(y_test, errors='coerce').astype(int)

# Calculate confusion matrix and accuracy.
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[95 15]
 [19 50]]


0.8100558659217877

In [111]:
# Convert y_test to numeric type, ensuring consistency with y_pred.
y_test = pd.to_numeric(y_test, errors='coerce').astype(int)

# Calculate confusion matrix and accuracy.
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred1)
print(cm)
accuracy_score(y_test, y_pred1)

[[108   2]
 [ 58  11]]


0.664804469273743

In [114]:
# Convert y_test to numeric type, ensuring consistency with y_pred.
y_test = pd.to_numeric(y_test, errors='coerce').astype(int)

# Calculate confusion matrix and accuracy.
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred2)
print(cm)
accuracy_score(y_test, y_pred2)

[[108   2]
 [ 58  11]]


0.664804469273743

In [ ]:
data=predic